pentoo-installer: add debug line in for troubleshooting

diff --git a/pentoo-installer/trunk/sbin/pentoo-installer b/pentoo-installer/trunk/sbin/pentoo-installer
--- a/pentoo-installer/trunk/sbin/pentoo-installer
+++ b/pentoo-installer/trunk/sbin/pentoo-installer
@@ -902,6 +902,9 @@ DIALOG --gauge "${3}" 6 75 0
         echo "Won the race, night night"
         sleep 1
     done
+    if ! [ -f /tmp/.unsquashfs-retcode ]; then
+        echo "This shouldn't be possible, /tmp/.unsquashfs-redcode is missing"
+    fi
     # alert the user to fatal errors
     #make sure we have a retcode
     if [ -n "$(cat /tmp/.unsquashfs-retcode)" ]; then
